### ISSUE TITLE
How to SKIP time steps

### ISSUE THREAD

**Issue by blazezhazha** [imatge-upc/skiprnn-2017-telecombcn#3]
Hi,
I have read several papers on _SENTENCE SIMPLIFICATION/SIMPLIFIED REPRESENTATIONS_, most of which usually SKIP words with discrete actions and learn the policy through Reinforcement Learning. However, in their implementation I find that the cell states are still computed on each time step. Thus hardly any time is saved during training or inference.
This research is very novel and interesting for it's the first time to modify RNN cells intrinsically to SKIP some information as far as I know, and what _IMPRESSED_ me most was that 
> **The number of skipped time steps can be computed ahead of time.**  

, which brings up the possibility that the cost of time and computation can be reduced by pre-calculating how many steps is to be skipped.
According to your method, at time step `t`, if `u_t` equals 1(state update at time t), then the step skipped  till next state update can be directly calculated with 
```python
skipped_steps = ceil(1.0 / simga(WS_t + b))
```
However, in your code of implementation, I am not able to find the corresponding snippets where this computed skipped time steps may be implemented :( . Did I miss it somehow?
If I want to skip the state representation together with the computation cost, must it be done by overriding the `dynamic_rnn` method, or is it already done somehow by optimization inside tensorflow implementation?
Thank you for your time!

**Comment by victorcampos7** [comment]
You are right, there is no current implementation of this. It might be relatively straightforward to implement for batch sizes of 1, but the batched case can be more tricky -- especially due to the static nature of TensorFlow. As you said, you would need to override the whole `dynamic_rnn` loop to account for the skipped steps in an efficient manner.

Months ago I tried to port the code to PyTorch to explore this possibility, but custom RNNs were extremely slow. This was done with a very early release (version 0.2, I think) and they might be faster now. This said, if you want to compete with the fastest implementations in terms of wall-clock time, implementing the cell in raw TF/PyTorch will not be enough (RNN implementations in cuDNN will always be faster). You would need some low-level CUDA implementation, e.g. with cupy as in [QRNN](https://github.com/salesforce/pytorch-qrnn/tree/master/torchqrnn) or [SRU](https://github.com/taolei87/sru/tree/master/sru).

**Comment by blazezhazha** [comment]
Okay, I'aware of this situation.
I'm gonna make some further digging on TF/PyTorch raw implementations, which seems a bit challenging for me, and try to find a way out about this `skip_step` feature some time.
Thank you again!
